#ifndef CONSTANTE_H_INCLUDED
#define CONSTANTE_H_INCLUDED

#define DIRECTION_HAUT 0
#define DIRECTION_BAS 1
#define DIRECTION_DROITE 2
#define DIRECTION_GAUCHE 3
#define DIRECTION_STOP 4


#define MILIEU_PERSONNAGE 60*1.4/2
#define TAILLE_PERSONNAGE 60

#define TAILLE_X 480
#define TAILLE_Y 640
#define TAILLE_VILLE 3000

#define DEPLACEMENT 4

#define DEMARRAGE_POS_PERSO_X 560
#define DEMARRAGE_POS_PERSO_Y 560


#endif // CONSTANTE_H_INCLUDED
